#!/usr/bin/env node
/* ============================================================
   test-balance.mjs — is a test balanced, and do its versions match?

   The new-test skill (step 1b) runs it on a draft before Daniel sees a paper; anyone can run it on
   a test already in the shared registry. It uses js/balance.js, the ONE rules file the private
   analysis page uses too (question 13), so test-making and the website can never disagree.

   It reads, and never writes anything but the files you name:
     · the shared registry, IG/AppScript/AppScript REFLECTION System/Code/2_Registry.gs (REFL_DIR=<folder> for another copy);
     · labs-shared/syllabus.json (2026–2028): the sub-topics and their points, Core or Supplement;
     · the reflection's getTopicYear (cut out of Code/Code.gs by name), which it compares with
       balance.js's copy on every point before it says anything: they must agree;
     · the Bio English keyword list (labs/bio-english-lab-source/keywords.master.js), to list a
       keyword from a topic not yet taught for a person to check (structured questions only:
       the registry holds no multiple-choice wording).

   node tools/test-balance.mjs                    every test in the registry, one row each
   node tools/test-balance.mjs "Test T7"          one test (a family or one version's id): its table, its versions
   node tools/test-balance.mjs --draft d.json     a draft: one map, or a list of maps (its versions), in
                                                  balance.js's MAP shape; a 6th item on a question row is
                                                  its wording, for the keyword check
   --own T7,T5      say which topics are the test's own (when its name does not)
   --html out.html  also write the picture the analysis page shows (a standalone page)
   --json           print the result as JSON
   --strict         exit 1 when anything is flagged
   --outline        rewrite js/syllabus-outline.js from labs-shared/syllabus.json
   --check-outline  exit 1 when js/syllabus-outline.js is out of date
   ============================================================ */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';
import vm from 'node:vm';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const HUB = resolve(REPO, '../..');
const IG = resolve(HUB, '..');
const RC = process.env.REFL_DIR || resolve(IG, 'AppScript/AppScript REFLECTION System/Code');
const require = createRequire(import.meta.url);
const Balance = require(resolve(REPO, 'js/balance.js'));

const argv = process.argv.slice(2);
const flag = n => argv.includes(n);
const opt = n => { const i = argv.indexOf(n); return i >= 0 ? argv[i + 1] : null; };
const positional = argv.filter((a, i) => !a.startsWith('--') && !['--draft', '--own', '--html'].includes(argv[i - 1]));

/* ---------- the syllabus outline ---------- */
const SYL = JSON.parse(readFileSync(resolve(HUB, 'labs-shared/syllabus.json'), 'utf8'))['2026-2028'];
const OUTLINE = Balance.outlineFrom(SYL);
const OUTLINE_FILE = resolve(REPO, 'js/syllabus-outline.js');
const outlineText = () =>
  '/* GENERATED by tools/test-balance.mjs --outline from labs-shared/syllabus.json (2026–2028): every topic, sub-topic\n' +
  '   and point NUMBER, with C (Core) or S (Supplement). Titles and numbers only, never a point\'s wording. Do not edit. */\n' +
  'window.SYLLABUS_OUTLINE = ' + JSON.stringify(OUTLINE) + ';\n';
if (flag('--outline')) { writeFileSync(OUTLINE_FILE, outlineText()); console.log('wrote js/syllabus-outline.js'); process.exit(0); }
if (flag('--check-outline')) {
  const ok = existsSync(OUTLINE_FILE) && readFileSync(OUTLINE_FILE, 'utf8') === outlineText();
  console.log(ok ? 'js/syllabus-outline.js matches labs-shared/syllabus.json' : 'js/syllabus-outline.js is OUT OF DATE: run node tools/test-balance.mjs --outline');
  process.exit(ok ? 0 : 1);
}

/* ---------- the reflection's school order: balance.js must agree with it on every point ---------- */
function cut(src, name) {
  const i = src.indexOf('function ' + name + '(');
  if (i < 0) throw new Error(name + ' not found in Code.gs');
  let d = 0, j = src.indexOf('{', i);
  for (let k = j; k < src.length; k++) { if (src[k] === '{') d++; else if (src[k] === '}' && --d === 0) return src.slice(i, k + 1); }
  throw new Error(name + ' has no end');
}
const CODE = readFileSync(resolve(RC, 'Code.gs'), 'utf8');
const getTopicYear = vm.runInNewContext('(' + cut(CODE, 'getTopicYear') + ')');
const POINTS = [];
for (const t of SYL.topics) for (const s of t.sections) for (const p of (s.core || []).concat(s.supplement || [])) POINTS.push(s.n + '.' + p.n);
const disagree = POINTS.filter(p => getTopicYear(p).year !== Balance.taughtYear(p));
if (disagree.length) {
  console.error('balance.js and the reflection\'s getTopicYear disagree on ' + disagree.length + ' point(s): ' + disagree.slice(0, 8).join(', ') +
                '\nThe school\'s order changed in the reflection: copy it into taughtYear in js/balance.js first.');
  process.exit(1);
}

/* ---------- the registry ---------- */
function registry() {
  const ctx = { console };
  vm.createContext(ctx);
  vm.runInContext(readFileSync(resolve(RC, '0_ActiveDefault.gs'), 'utf8') + '\n' + readFileSync(resolve(RC, '2_Registry.gs'), 'utf8') +
                  '\n;this.__R = ASSESSMENT_REGISTRY;', ctx);
  return ctx.__R;
}

/* ---------- later keywords (structured questions only) ---------- */
let KEYWORDS = null;
/* keywords that are also everyday words in a question ("a light source"): listing them would be noise */
const EVERYDAY = new Set(['source', 'sink']);
async function keywords() {
  if (KEYWORDS) return KEYWORDS;
  const f = resolve(HUB, 'labs/bio-english-lab-source/keywords.master.js');
  if (!existsSync(f)) return (KEYWORDS = []);
  const m = await import(pathToFileURL(f).href);
  KEYWORDS = (m.KEYWORDS || []).filter(k => k.year !== 'IB' && k.en).map(k => ({
    term: String(k.en).replace(/\s*\(.*?\)\s*/g, ' ').trim(),
    at: (/^\d+\.\d+$/.test(String(k.subtopic)) ? String(k.subtopic) : String(k.topic) + '.1') + '.1'   // its sub-topic decides the year it is taught
  })).filter(k => k.term.length >= 4 && Balance.topicNum(k.at) >= 1 && Balance.topicNum(k.at) <= 21   // topic 0 is the skills list
    && !EVERYDAY.has(k.term.toLowerCase()));
  return KEYWORDS;
}
function laterKeywords(map, b, texts) {
  const ownNums = b.own.map(k => +k.slice(1)), maxOwn = Math.max(0, ...ownNums), out = [];
  const taught = at => { const y = Balance.taughtYear(at), t = Balance.topicNum(at); return y < map.yg || (y === map.yg && t <= maxOwn) || ownNums.includes(t); };
  const known = new Set(KEYWORDS.filter(k => taught(k.at)).map(k => k.term.toLowerCase()));
  /* a taught keyword is taken out of the wording first, longest first, so "gall bladder" (7.2) is never read as
     "bladder" (13.1) */
  const taughtTerms = KEYWORDS.filter(k => taught(k.at)).map(k => k.term).sort((a, z) => z.length - a.length);
  const esc = t => t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  for (const [qid, text] of Object.entries(texts)) {
    let words = String(text || '').replace(/<[^>]+>/g, ' ');
    for (const t of taughtTerms) words = words.replace(new RegExp('\\b' + esc(t) + '\\b', 'gi'), ' ');
    for (const k of KEYWORDS) {
      if (taught(k.at) || known.has(k.term.toLowerCase())) continue;
      const re = new RegExp('\\b' + esc(k.term) + '\\b', 'i');
      if (re.test(words)) out.push({ q: qid, term: k.term, topic: Balance.topicNum(k.at) });
    }
  }
  return out;
}

/* ---------- printing ---------- */
const r1 = x => Math.round(x * 10) / 10, r0 = x => Math.round(x);
const pad = (s, n) => String(s).padEnd(n), lpad = (s, n) => String(s).padStart(n);
function printOne(b, kws) {
  console.log('\n' + b.name + (b.ver ? '  (version ' + b.ver + ')' : '') + '  ·  ' + b.id);
  console.log('  Year ' + b.yg + ' · ' + (b.type || 'test') + ' · ' + b.total + ' marks · its own topics: ' + b.own.join(', '));
  console.log('  Where the marks are: own topics ' + r1(b.cat.own) + ' (' + r0(b.ownPct) + ' %) · earlier topics ' + r1(b.cat.earlier) +
              ' · AO3 ' + r1(b.cat.ao3) + ' (' + r0(b.ao3Pct) + ' %; the whole 0610 qualification: ' + Balance.AO3_QUALIFICATION + ' %) · not yet taught ' + r1(b.cat.late) +
              (b.cat.unmapped ? ' · not mapped ' + r1(b.cat.unmapped) : ''));
  console.log('  ' + pad('Sub-topic', 46) + lpad('MCQ', 6) + lpad('Structured', 12) + '   ' + pad('Points', 9) + 'Flag');
  for (const r of b.subs) {
    const flagW = r.miss ? 'not covered' : r.heavy ? 'heavy' : '';
    console.log('  ' + pad((r.n + ' ' + r.l).slice(0, 45), 46) + lpad(r1(r.mcq), 6) + lpad(r1(r.wr), 12) + '   ' + pad(r.covN + ' of ' + r.sts.length, 9) + flagW);
  }
  console.log('  ' + pad('Earlier topics', 46) + lpad('', 18) + '   ' + r1(b.cat.earlier) + ' marks');
  console.log('  ' + pad('AO3 practical skills', 46) + lpad('', 18) + '   ' + r1(b.cat.ao3) + ' marks');
  console.log('  ' + pad('Not yet taught', 46) + lpad('', 18) + '   ' + (b.cat.late ? '⚠ ' + r1(b.cat.late) + ' marks' : '—'));
  console.log('  Points covered: Core ' + b.core[0] + ' of ' + b.core[1] + ' · Supplement ' + b.supp[0] + ' of ' + b.supp[1] +
              ' · an even share is ' + r1(b.even) + ' marks per sub-topic (heavy above ' + r1(b.even * Balance.LIMITS.heavy) + ')');
  const flags = Balance.flagsOf(b).concat((kws || []).map(k => 'question ' + k.q + ' uses “' + k.term + '” (topic ' + k.topic + ', not yet taught): fine only in passing'));
  console.log(flags.length ? '  To look at:\n    · ' + flags.join('\n    · ') : '  Nothing to look at.');
  return flags.length;
}
function printVersions(bs) {
  const vc = Balance.versions(bs);
  if (!vc) return 0;
  console.log('\n  Versions ' + vc.versions.join(', ') + ' (a flag: more than ' + Balance.LIMITS.versionGap + ' marks apart)');
  console.log('  ' + pad('Marks on…', 24) + vc.versions.map(v => lpad(v, 8)).join(''));
  for (const r of vc.rows) console.log('  ' + pad(r.l, 24) + r.vals.map(v => lpad(v, 8)).join('') + '   ' + (r.flag ? '⚠ ' + r.gap + ' apart' : '✓'));
  return vc.flagged.length;
}

/* ---------- the picture (the page's own drawing code) ---------- */
function writeHtml(file, bs) {
  const A = require(resolve(REPO, 'js/analysis.js'));
  const css = readFileSync(resolve(REPO, 'css/analysis.css'), 'utf8');
  const parts = bs.map(b => '<section class="panel" style="margin:18px 0"><h2>' + A.esc(b.name) + (b.ver ? ' · version ' + A.esc(b.ver) : '') + '</h2>' +
    A.balancePanelHtml(b, Balance.versions(bs), 720, OUTLINE) + '</section>').join('');
  writeFileSync(file, '<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><title>Test balance</title><style>' + css +
    '</style></head><body><div class="page" style="padding-top:20px">' + parts + '</div></body></html>');
  console.log('\nwrote ' + file);
}

/* ---------- run ---------- */
const own = opt('--own') ? opt('--own').split(',').map(s => s.trim().toUpperCase().replace(/^(\d)/, 'T$1')) : null;
await keywords();
let flagged = 0, results = [];
if (opt('--draft')) {
  const raw = JSON.parse(readFileSync(resolve(process.cwd(), opt('--draft')), 'utf8'));
  const maps = (Array.isArray(raw) ? raw : [raw]).map((m, i) => Object.assign({ v: 1, id: m.id || 'draft' + (i + 1), q: [] }, m, own ? { own } : {}));
  const bs = maps.map(m => Balance.balance(m, OUTLINE));
  bs.forEach((b, i) => {
    const texts = {}; (maps[i].q || []).forEach(q => { if (q[1] === 's' && q[5]) texts[q[0]] = q[5]; });
    flagged += printOne(b, laterKeywords(maps[i], b, texts));
  });
  flagged += printVersions(bs);
  results = bs;
  if (opt('--html')) writeHtml(resolve(process.cwd(), opt('--html')), bs);
} else {
  const R = registry();
  const maps = Object.keys(R).map(id => Object.assign(Balance.fromRegistry(id, R[id]), own ? { own } : {}));
  const fams = Balance.families(maps);
  const want = positional[0];
  if (want) {
    const fam = fams.find(f => f.some(m => m.id === want || m.fam === want));
    if (!fam) { console.error('No test "' + want + '" in the registry. Its ids: ' + maps.map(m => m.id).join(', ')); process.exit(1); }
    const one = fam.some(m => m.id === want) && !fam.some(m => m.fam === want) ? fam.filter(m => m.id === want) : fam;
    const bs = one.map(m => Balance.balance(m, OUTLINE));
    bs.forEach((b, i) => {
      const qm = R[one[i].id].questionMap || {}, texts = {};
      Object.keys(qm).forEach(k => { texts[k] = qm[k].text || ''; });
      flagged += printOne(b, laterKeywords(one[i], b, texts));
    });
    flagged += printVersions(fam.length > 1 ? fam.map(m => Balance.balance(m, OUTLINE)) : bs);
    results = bs;
    if (opt('--html')) writeHtml(resolve(process.cwd(), opt('--html')), bs);
  } else {
    console.log(pad('Test', 34) + lpad('Own %', 7) + lpad('Sub-topics', 12) + lpad('Points', 10) + '  ' + pad('Heaviest', 18) + lpad('AO3 %', 7) + lpad('Late', 7) + '  Versions');
    for (const fam of fams) {
      const bs = fam.map(m => Balance.balance(m, OUTLINE)), vc = Balance.versions(bs);
      bs.forEach((b, i) => {
        const fl = Balance.flagsOf(b).length;
        flagged += fl;
        const hv = b.heaviest ? b.heaviest.n + ' ' + r0(b.cat.own ? b.heaviest.m / b.cat.own * 100 : 0) + '%' + (b.heaviest.heavy ? ' ⚠' : '') : '—';
        console.log(pad(b.id.slice(0, 33), 34) + lpad(r0(b.ownPct) + (b.ownPct < Balance.LIMITS.ownShare ? '⚠' : ''), 7) +
          lpad(b.subsHit + '/' + b.subs.length, 12) + lpad(b.nCov + '/' + b.nSt, 10) + '  ' + pad(hv, 18) + lpad(r0(b.ao3Pct), 7) +
          lpad(b.cat.late ? '⚠' + r1(b.cat.late) : '—', 7) + '  ' + (i ? '' : !vc ? 'one version' : vc.flagged.length ? '⚠ ' + vc.flagged.map(r => r.l.toLowerCase()).join(', ') : '✓ ' + vc.versions.join(', ')));
      });
      if (vc) flagged += vc.flagged.length;
      results = results.concat(bs);
    }
    console.log('\nOne test in full: node tools/test-balance.mjs "<its id or family>"');
  }
}
if (flag('--json')) console.log(JSON.stringify(results.map(b => Object.assign({}, b, { flags: Balance.flagsOf(b) })), null, 1));
process.exit(flag('--strict') && flagged ? 1 : 0);
